dataset: cifar100

model: icarl
# convnet: rebuffi
convnet: myclip
convnet_config:
  clip_weight_name: RN50
  clip_trainable: False

lr: 2.
weight_decay: 0.00005
# scheduling:
#   - 49
#   - 63
# lr_decay: 0.2
optimizer: sgd
epochs: 1


dataset_transforms:
  clip: true

