dataset: cifar100

model: icarl
# convnet: rebuffi
convnet: myclip
convnet_config:
  clip_weight_name: RN50
  clip_trainable: True

lr: 0.1
weight_decay: 0.0005
# scheduling:
#   - 49
#   - 63
# lr_decay: 0.2
optimizer: sgd
epochs: 10


dataset_transforms:
  clip: true

